development:
  adapter: postgresql
  encoding: unicode
  database: flightchord
  pool: 4
  username: shaz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 4
  username: shaz
  password:
